// @ts-check
import { defineConfig } from "astro/config";
import sitemap from "@astrojs/sitemap";
import tailwind from "@astrojs/tailwind";
import playformCompress from "@playform/compress";
import icon from "astro-icon";
import robotsTxt from "astro-robots-txt";

// https://astro.build/config
export default defineConfig({
	output: "static",
	site: "https://cficonline.com",
	trailingSlash: "never",
	prefetch: true,
	integrations: [
		sitemap(),
		tailwind(),
		icon(),
		robotsTxt({
			policy: [
				// Default
				{ userAgent: "*", allow: ["/"], crawlDelay: 999_999 },

				// AI bots
				...[
					"008",
					"360Spider",
					"adbeat_bot",
					"AdsBot-Google-Mobile",
					"AdsBot-Google",
					"AI2Bot",
					"aiHitBot",
					"AlexandriaOrgBot",
					"Amazonbot",
					"AndersPinkBot",
					"anthropic-ai",
					"Applebot-Extended",
					"Applebot",
					"archive.org_bot",
					"ArchiveBot",
					"Arquivo-web-crawler",
					"Atom Feed Robot",
					"AwarioBot",
					"AwarioSmartBot",
					"Baiduspider",
					"bingbot",
					"BitSightBot",
					"Blackboard",
					"BrandVerity",
					"Bytespider",
					"CCBot",
					"ChatGPT-User",
					"Cincraw",
					"ClaudeBot",
					"coccocbot-web",
					"cohere-ai",
					"cohere-training-data-crawler",
					"Dataprovider.com",
					"Daum",
					"dcrawl",
					"Diffbot",
					"DuckAssistBot",
					"DuckDuckBot",
					"DuckDuckGo-Favicons-Bot",
					"ev-crawler",
					"FacebookBot",
					"Feedfetcher-Google",
					"Google Favicon",
					"Google-Extended",
					"Google-Safety",
					"Googlebot-Image",
					"Googlebot-Mobile",
					"Googlebot-News",
					"Googlebot-Video",
					"Googlebot",
					"GoogleOther",
					"GPTBot",
					"HaoSouSpider",
					"HeadlessChrome",
					"heritrix",
					"HTTrack 3.0",
					"HTTrack",
					"HubSpot",
					"ia_archiver-web.archive.org",
					"ia_archiver",
					"ImagesiftBot",
					"IonCrawl",
					"Jugendschutzprogramm-Crawler",
					"Kangaroo Bot",
					"KStandBot",
					"LightspeedSystemsCrawler",
					"linkfluence",
					"LinkWalker",
					"magpie-crawler",
					"Mediapartners-Google",
					"Mediatoolkitbot",
					"Meta-ExternalAgent",
					"Meta-ExternalFetcher",
					"MetaInspector",
					"MojeekBot",
					"msnbot-media",
					"msnbot",
					"MuckRack",
					"NetcraftSurveyAgent",
					"Netvibes",
					"newspaper",
					"Nicecrawler",
					"Nutch",
					"OAI-SearchBot",
					"Offline Explorer",
					"omgili",
					"Omgilibot",
					"OpenindexSpider",
					"Pandalytics",
					"PanguBot",
					"panscient.com",
					"PerplexityBot",
					"PetalBot",
					"proximic",
					"Qwantbot",
					"Qwantify",
					"scoop.it",
					"Scrapy",
					"SeekportBot",
					"SemanticScholarBot",
					"SeznamBot",
					"SMTBot",
					"Sogou web spider",
					"teoma",
					"Timpibot",
					"TinEye-bot",
					"TinEye",
					"trendictionbot",
					"TrendsmapResolver",
					"Turnitin",
					"TurnitinBot",
					"TweetmemeBot",
					"Twingly",
					"um-LN",
					"VelenPublicWebCrawler",
					"virustotal",
					"Webzio-Extended",
					"Webzio",
					"yacybot",
					"Yahoo! Slurp",
					"Yandex",
					"YandexBot",
					"YandexImages",
					"YandexRenderResourcesBot",
					"Yeti",
					"YisouSpider",
					"YouBot",
					"ZoominfoBot",
					"ZumBot",
				].map((bot) => ({
					userAgent: bot,
					disallow: ["*"],
					crawlDelay: 999_999
				})),
			]
		}),
		playformCompress(),
	],
	experimental: {
		contentIntellisense: true,
	},
});
